services:
  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    ports: 
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./services:/app/services
      - ./app.py:/app/app.py
      - ./socket_manager.py:/app/socket_manager.py
      - ./redis_client.py:/app/redis_client.py
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FRONTEND_URL=http://localhost:5173
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
  
  # backend2:
  #   build:
  #       context: .
  #       dockerfile: Dockerfile
  #   ports:
  #     - "5001:5000"
  #   volumes:
  #     - ./controllers:/app/controllers
  #     - ./models:/app/models
  #     - ./services:/app/services
  #     - ./app.py:/app/app.py
  #     - ./socket_manager.py:/app/socket_manager.py
  #     - ./redis_client.py:/app/redis_client.py
  #   environment:
  #     - FLASK_APP=app.py
  #     - FLASK_ENV=production
  #     - FRONTEND_URL=http://localhost:5173
  #     - DB_URI=${DB_URI}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - REDIS_URL=redis://redis:6379
  #     - REDIS_HOST=redis
  
  frontend:
    build:
      context: ./views
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./views:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080 # nginx external port
      - VITE_SOCKET_URL=http://localhost:8080
volumes: # needed to avoid missing module error
  node_modules: {}